# This is a basic workflow to help you get started with Actions

name: Scrape daily data

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:  
  pull_request:
  workflow_dispatch:
  schedule: '1 * * * '

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl "https://apidatos.ree.es/datos/mercados/precios-mercados-tiempo-real?start_date=`date --iso-8601`T00:00&end_date=`date --iso-8601`T23:59&time_trunc=hour" | tee  data.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
